[package]
name = "shmarks"
version = "0.1.6"
edition = "2021"
authors = ["Belkanov Dmitriy <dbkkll@yandex.ru>"]
description = "Directory bookmarks for the shell"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["cargo"] }
dirs = "5.0.1"
nu-ansi-term = "0.49.0"
regex = "1.10.2"
thiserror = "1.0.51"
toml = "0.8.8"
